 figure
uicontrol('style','text', ...
          'units','pixel', ...
          'position',[19 19 122 14], ...
          'backgroundcolor',[.95 .95 .95]);
h = uicontrol('style','text', ...
              'units','pixel', ...
              'position',[20 20 120 12], ...
              'backgroundcolor',[.4 .4 .4], ...
              'foregroundcolor',[.95 .95 .95]);
%
for i=1:80
   pos = get(h,'position');
   % der Balken ist maximal 120 pixel lang
   pos(3) = i/80*120;
   set(h,'position',pos,'string',sprintf('%.0f%%',i/80*100))
   drawnow
   %
   %%% Hier kommt Dein Code %%%
   pause(0.05)
   %%%%%%%%%%%%%%%%%%%%%%%%%%%%
   %
end 